### PR TITLE
winter river in pyhton

### PR DESCRIPTION
**Pull request by aoloe**

### CODE REVIEW

**Comment by duchonic** [comment]
Hi ale, i found a bug!

`print('s:' + str(occurrences['s']) + ' has the same occurence as t:' + str(occurrences['t']) + ' => t and s should both be at 3th place !!! ')`

**Comment by duchonic** [comment]
This is a test from the CLI gh pr comment

**Comment by duchonic** [comment]
we could change the dict from letter, nr_occurance to nr_occurance, letters


```python
def rank(occurrences):
    ranking = {}
    for key, value in occurrences.items(): 
        try:
            ranking[value] += ', ' + key
        except:
            ranking[value] = key
    return ranking
```

**Comment by aoloe** [comment]
well, i'm not sure that this simple solution should really take care of it.

i would put there a comment and suggest the reader to discuss how this should be solved...
personally, i think i would solve it, by replacing the slicing by a `get_top-n()` function, that might return more than n results if there is a tie...

**Comment by roseTech** [comment]
Thank you very much!

**Pull request merged**
